epiforecasts/covidregionaldata

- R/colombia.R
- R/covid19R_wrappers.R
- R/get_iso_codes.R
- R/get_region_codes.R
- R/get_regional_data.R
- R/utils.R
- tests/testthat/custom_tests/mock_data.R
- tests/testthat/test-get_colombia_regional_cases.R
- tests/testthat/test-get_regional_data.R
- tests/testthat/test-utils.R
Changes to ISO codes so that:
> Internally, the variables are called "level_1_region_code" and "level_2_region_code"
> These are renamed as the final step before the data is returned to the user
> This means we can now use custom names for the region codes rather than just calling it iso_code
> also, I edited the Covid19R wrappers.
> Location codes changes

- DESCRIPTION
got caught out again with the old version of tidyr we have as our default... It fails with an unknown method that is only introduced in v1
> Specify tidyr version

- R/get_national_data.R
- R/national.R
- tests/testthat/test-get_national_data.R
This PR resolves the issue of not all countries having assigned regions as flagged in #68 by @tjtnew.
There were two issues in play. 
1. ECDC data uses a European standard ISO code (I think this is a new change) that has several differences from what `countrycode` supports. Resolved this using a manual check for 4 instances. 
2. In `get_national_data` countries should have had any missing regions checked and filled if present for any dates. This was coded as an up directional fill when it should really have been bidirectional. This issue impacted both the WHO and ECDC data sets. 
PR also adds tests based on the reprex in #68 to flag if this issue occurs in the future. CRAN check run locally with no issues.
> Resolves issue with not all countries having a region 

- R/get_regional_data.R
- R/uk.R
English regions only have deaths available by date of death.
- Adding as 2 new variables to data import (newDeaths28DaysByDeathDate and cumulative)
- Updating the "deaths_new" and "deaths_total" columns (as with cases)
- Regions are by date of death, nations are by date of report
(Also reverts commit in PR #69 for localised region codes. PR closed)
> UK deaths data

- tests/testthat/test-get_brazil_regional_cases.R
- tests/testthat/test-get_germany_regional_cases.R
- tests/testthat/test-utils.R
Some fixes to out of date tests which were causing checks to fail.
- Brazil data are present and up to date but test was out of date (old url for data source) - fixed.
- More general test for German level 2 kreise areas (there are technically 401 although data source reports 412, so we might expect some variation)
- The "convert to Covid19R format" function is currently failing checks. With limited time I am temporarily ignoring the problem (ie skip test on CRAN). We don't use this functionality in our work, and not sure if it is used elsewhere. If the problem is not a straightforward fix and/or recurs we may want to drop this functionality.
In general the tests look a bit over-specific to me, as @seabbs raised in #78 . I'm planning to work on a better system for checking data sources, so …
> Test fixes

- DESCRIPTION
- NEWS.md
- R/uk.R
- tests/testthat/test-get_uk_regional_cases.R
This PR converts UK data extraction to V2 of the API (which is currently undocumented but can be explored [here](https://coronavirus.data.gov.uk/details/download)). 
This may enable the addition of new variables but the full list and documentation has yet to be published. 
This PR also adds the ability to extract archived UK data either from the V2 API since April or for NHS regions for the last two weeks. This may be helpful when evaluating forecasting models (as it is important to fit to the data available at the time and not the final data set) and when exploring evidence for data truncation. 
Tests have been extended for this new feature but in addition the test for the number of available UTLAs had to be dropped from 200 0> 49. It is unclear what has led to this change but it appears …
> Convert to api v2 UK

- R/uk.R
- R/utils.R
- tests/testthat/test-get_uk_regional_cases.R
- Looks like NHS data archived only for last 7 days (instead of 14). Checked by trial and error - couldn't find clear evidence of this policy so could be wrong/change. This was causing UK testthat checks to fail
- Stopped downloading admissions by age and MV beds. These variables are given for national level only (not regional) and in long (not wide) format which had trouble slotting in to the standardised structure for returning dataframes. Removed as not currently used by us (I think), but can reinstate: if so, suggest re-writing as an option which returns a more suitable custom dataset structure
> UK NHS archive data fix

- R/shared-methods.R
- man/check_country_available.Rd
- tests/testthat/test-check_country_available.R
suggestions only - minor edits to `shared-methods.R`
- returns message: "Getting data for ... at ... administrative region"
- quite wordy, suggest replace with "getting data for ... by ..." which should still make sense
- replaced "getting" with "Processing" to be clear we aren't returning the raw data directly
- arg : `level = "2"`
- giving this arg as a character is not very intuitive - used numeric
- `available` was misspelled in several places
> typo fix + suggestions

- .github/workflows/germany.yaml
- README.md
- inst/WORDLIST
This PR adds the Germany Github action missed in #172. It currently does nothing as the testing file has not yet been reimplemented.
> Germany GitHub Actions

- R/get_region_codes.R
- R/lithuania.R
- man/get_lithuania_level_2_codes.Rd
- man/get_lithuania_region_codes.Rd
- man/get_lithuania_regional_cases_only_level_1.Rd
I've changed how regions and region codes are used internally to get from the source (which provides municipality names) to what we need (knowing which municipalities are in which counties, and applying ISO:3166-2 codes for municipalities and counties). This should be invisible to the end-user but is cleaner and should ask for fewer `left_join` calls.
> Refactor how regions are manipulated in Lithuania code

- R/Italy.R
This PR fixes the warning seen when cleaning Italy data. 
This looks like a false warning from `dplyr` based on the use of `data` as a variable. Given that and after checking I have suppressed it. This could be dangerous if the date variable changes format but tests should catch this.
> Fix Italy warning

- R/utils.R
- man/csv_reader.Rd
This PR looks to mitigate #117 by increasing the default `guess_max` to `1000` and surfacing it as an argument to be used when implementing new data sources. 
This would be the preferred solution vs using `readr` as `covidregionaldata` is already very dependency heavy and it would be nice to stop this getting worse.
> surface guess_max from vroom and increase default

- tests/testthat/test-check_country_class.R
Made a small change to the testing functions so they show the country name, trying to get this from the class didn't work as they were not initialized. If they are initialized then you can't get the public fields.
Fixes issue #203
> Check class bugfix 203

- R/Canada.R
- R/CountryTemplate.R
- R/ECDC.R
- R/Germany.R
- R/Italy.R
- R/Mexico.R
- R/UK.R
- R/WHO.R
- R/shared-methods.R
- man/Canada.Rd
- man/DataClass.Rd
- man/ECDC.Rd
- man/Germany.Rd
- man/Italy.Rd
- man/Mexico.Rd
- man/UK.Rd
- man/WHO.Rd
This PR demonstrates moving `data_urls` to a list based structure that is created at initialisation from `common_data_urls` (shared across levels) and `level_data_urls` which is stratified by level. It is based on discussions in #231 with @RichardMN using the nested implementation approach vs using a field per level. The advantage of this is nesting any number of levels and easily dispatching to the correct level without custom if else initialisation code. This is open for debate. 
I have checked all changes locally using `options(testDownload = TRUE)` and completed all other PR checks as specified.
> Alt data urls

- R/shared-methods.R
- tests/testthat/test-CountryDataClass.R
- tests/testthat/test-DataClass.R
Adds tests for missing edge cases after looking at the coverage report + adds tests for the CountryDataClass specific methods.
> Extend dataclass tests

- R/India.R
<del> Bug seems to be caused by not including "cases_new" on the full join, creating .x and .y versions. </del>
Bug actually caused by `pivot_longer(-Date, names_to = "state", values_to = "cases_new")` which is putting everything in cases_new. Fixed now.
> fixed the .x and .y on join bug in India

- R/Mexico.R
made an alteration to change 'estados' and 'municipios' to 'estado' and 'municipio' in `supported_region_names`.
> changed 'estados' and 'municipios' to 'estado' and 'municipio'

- R/Mexico.R
Somehow the download url snippets for states and municipalities had been switched in the Mexico code so we downloaded data for states then put it through the municipalities logic, and vice versa.
I think this fixes the problem identified in #119 
This PR should be applied subsequent to #297
> Fix for region glitch in Mexico code as seen in #119

- .gitignore
- R/Cuba.R
There was a typo in an ISO 3166-2 code for one Cuban region. This fixes that.
> Fix for Cuban region code error identified in #119

- R/Lithuania.R
This is a fix for #341 to re-order the content of the `initialize` method so that optional params are saved into the public fields before calling `super$initialize`.
> Reorder Lithuania$initialize so params are respected

- vignettes/slowstart.Rmd
On a related note, why is this vignette set to `eval = FALSE`? Using `eval = TRUE` would prevent this kind of errors and ensure the displayed output match the real output (even after updates).
> Fix argument name in vignette

- R/get_available_datasets.R
Without this, an error as in #369 still occurs when calling a function without loading the library first.
> qualify covidregionaldata when loading available datasets

- R/Germany.R
The code as implemented counts every row in the case/death data just once, as if it was a line list of individuals - instead it is relatively finely resolved count data which needs to be summed up.
This is causing problems downstream https://github.com/epiforecasts/covid/issues/184
> fix Germany case/death data

- _pkgdown.yml
This PR switches to bootstrap 5 as supported by the latest version of `pkgdown` local inspection shows no issues (and @Bisaloo was also able to render the site without issues). PR linked to #440
> Switch to bootstrap 5 for pkgdown

- _pkgdown.yml
The url field must contain a valid URL. The current setup is causing some issues with the search feature because the resulting sitemap is incorrect: 
https://github.com/epiforecasts/covidregionaldata/blob/0a910316135fb5768e6afbe7ec8c7297a9bd4d6c/sitemap.xml
> Fix website URL

- .github/workflows/R-CMD-check.yaml
There is a gap in our coverage where we jump directly from `oldrel-1` to `release`. 
This is also a problem because `oldrel` is defined as a required test to merge PRs. Since this test doesn't exist, PRs never reach the stage where they can be merged (excepted if an admin bypasses the test requirements).
> Add oldrel R CMD check

- .github/workflows/Belgium.yaml
- .github/workflows/Brazil.yaml
- .github/workflows/Canada.yaml
- .github/workflows/Colombia.yaml
- .github/workflows/Covid19DataHub.yaml
- .github/workflows/Cuba.yaml
- .github/workflows/ECDC.yaml
- .github/workflows/Estonia.yaml
- .github/workflows/France.yaml
- .github/workflows/Google.yaml
- .github/workflows/India.yaml
- .github/workflows/Italy.yaml
- .github/workflows/JHU.yaml
- .github/workflows/JRC.yaml
- .github/workflows/Lithuania.yaml
- .github/workflows/Mexico.yaml
- .github/workflows/Netherlands.yaml
- .github/workflows/SouthAfrica.yaml
- .github/workflows/Switzerland.yaml
- .github/workflows/UK.yaml
- .github/workflows/USA.yaml
- .github/workflows/WHO.yaml
This allows us to update workflows for all sources by changing a single file (`test-regional-datasets.yml`).
It still feels a little bit strange to have a single file for each data source. A single workflow with a matrix dispatch might be a better approach. But I can't think of getting a badge for each element of the matrix :thinking:
> Call reusable action from all workflows
