tests/testthat/test-get_afghan_regional_cases.R, tests/testthat/test-get_belgium_regional_cases.R, tests/testthat/test-get_brazil_regional_cases.R, tests/testthat/test-get_canada_regional_cases.R, tests/testthat/test-get_germany_regional_cases.R, tests/testthat/test-get_india_regional_cases.R, tests/testthat/test-get_italy_regional_cases.R
This will flag up that a data source has stopped being updated
=> Update tests to ensure data sources have been updated recently

R/india.R, man/get_india_regional_cases.Rd
Before
```
pacman::p_load_gh("epiforecasts/covidregionaldata")
✓  checking for file ‘/tmp/RtmpcTq394/remotes64bb636c3253/epiforecasts-covidregionaldata-11c7f31/DESCRIPTION’ ...
─  preparing ‘covidregionaldata’:
✓  checking DESCRIPTION meta-information ...
Warning: /tmp/RtmpzxDxug/Rbuild73346c71eecf/covidregionaldata/man/get_india_regional_cases.Rd:10: unknown macro '\function'
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘covidregionaldata_0.4.0.tar.gz’
* installing *source* package ‘covidregionaldata’ ...
** using staged installation
** R
** byte-compile and prepare package for lazy loading
** help
Error : (converted from warning) /tmp/RtmpE5h0pv/R.INSTALL73456e313dae/covidregionaldata/man/get_india_re …
```
=> Fix link causing installation problem (#7)

tests/testthat/test-get_afghan_regional_cases.R, tests/testthat/test-get_belgium_regional_cases.R, tests/testthat/test-get_brazil_regional_cases.R, tests/testthat/test-get_canada_regional_cases.R, tests/testthat/test-get_colombia_regional_cases.R, tests/testthat/test-get_germany_regional_cases.R, tests/testthat/test-get_india_regional_cases.R, tests/testthat/test-get_interventions_data.R, tests/testthat/test-get_italy_regional_cases.R, tests/testthat/test-get_national_data.R, tests/testthat/test-get_regional_data.R, tests/testthat/test-get_russia_regional_cases.R, tests/testthat/test-get_uk_regional_cases.R, tests/testthat/test-get_us_regional_cases.R
all tests skipped where they require data to be downloaded
=> skip tests on cran

.github/workflows/check-full.yaml, tests/testthat/custom_tests/mock_data.R, tests/testthat/test-utils.R
* Changed input data to tibble to match expected input.
=> tweak test data for old release test

DESCRIPTION, R/canada.R, R/colombia.R, R/germany.R, R/india.R, man/get_canada_regional_cases.Rd, man/get_colombia_regional_cases.Rd, man/get_germany_regional_cases_only_level_1.Rd, man/get_india_regional_cases.Rd
- DESCRIPTION - added all data sources to Description
- Canada, Colombia, Germany, India - updated data sources in @description
=> updated data sources

R/uk.R, tests/testthat/test-get_uk_regional_cases.R
=> fix uk level 1

DESCRIPTION, R/national.R, tests/testthat/test-get_national_data.R
Updates for next release. Addresses issue #45
=> release 0.6.0

R/uk.R
Area types updated to match data
=> add new region names for UK area types

R/covid19R_wrappers.R, _pkgdown.yml
=> updates pkgdown and adds country name to info fn

DESCRIPTION, NEWS.md, R/get_linelist.R, R/utils.R, README.md, man/get_linelist.Rd
Clean up linelist code a little
- Adds outcome (death, T/F) to returned data
- Adds delays from onset to admission, death, and report to returned data
=> Clean linelist

R/brazil.R
- Fixed link to data source
- Checked data are in identical format and code still downloads and cleans correctly
=> Brazil - fix broken link

R/india.R
Date_YMD
This meant that the pivot_longer call would no longer work, so its best to remove the Date_YMD column. I've done this by only selecting the Date and state codes, which also removes the Status and TT columns.
The number of state codes in state_names and the number of columns match (==38)
=> Looks like the India data had some new columns:

R/get_interventions_data.R
Thus replacing sheet name with what I think should be the correct one. These fixes are pretty minor, are there any issues you'd like me to put a bit more effort into? I have a little time over the next few days.
=> The 'Database' sheet name does not exist in the download

R/uk.R
fixes https://github.com/epiforecasts/covid-rt-estimates/issues/131
=> fixed NHS statistics data source

R/uk.R
I think it would be good to have that choice - implemented here.
=> UTLA/LTLA switch in the UK

DESCRIPTION
I added my details to the DESCRIPTION file as a colaborator.
=> Updated my details to the Description file

DESCRIPTION
Made a mistake on branch DESCRIPTION, misspelled ctb as cbt which caused errors. Fixed it now.
=> Fixed error in DESCRIPTION

R/afghanistan.R
Resolves line length issues in linting.
=> Fix line length issue

.lintr
=> add increase linting line length to 120 char

tests/testthat/test-get_available_datasets.R
Tests for `get_avaliable_datasets()` #162
=> 162 test get avaliable datasets

R/get_available_datasets.R, R/get_national_data.R, R/get_regional_data.R, R/shared-methods.R, inst/WORDLIST, tests/testthat/test-country_R6_objects.R, tests/testthat/test-get_available_datasets.R
Fixing a typo, removing it from the WORDLIST
=> Spell check replace avaliable -> available

R/Mexico.R
When writing progress messages for the general functions I forgot Mexico has a custom download which needed verbose switches in. Added these now.
=> Added progress messages for Mexico download.

.github/workflows/Canada.yaml, .github/workflows/Colombia.yaml, .github/workflows/Cuba.yaml
Adds yaml github workflows for missing countries on dev (Canada, Cuba, Colombia)
=> added yaml files

R/shared-methods.R
This fixes #262 
I think I wrote the problematic code initially and I suspect I also reviewed it. Apologies.
=> Fix for common data url logic

R/UK.R, inst/WORDLIST, man/UK.Rd
changes `download_uk` to `download_filter`
closes #279
=> renames download_uk

NEWS.md, R/UK.R, inst/WORDLIST
updated news with a section outlining changes to the data since 0.8.3.
Added from @RichardMN's great work [outlining changes](https://github.com/epiforecasts/covidregionaldata/issues/119#issuecomment-822733608)
=> updated news with a data changes section

vignettes/slowstart.Rmd
=> Update mention of drat to recommend r-universe instead

README.Rmd, README.md
I think we mean "insightful" instead of "inciteful".
=> Spelling fix in Readme

inst/paper/paper.md
=> Fixing paper formatting.

R/UK.R, R/processing.R, R/test-DataClass.R, R/utils.R, data-raw/vietnam_codes.R
so we don't get nagged with annotations on PRs
=> Fix lintr warnings

R/shared-methods.R, tests/testthat/test-regional-datasets.R
=> Bug 454 countrycode

.github/workflows/Belgium.yaml, .github/workflows/Brazil.yaml, .github/workflows/Canada.yaml, .github/workflows/Colombia.yaml, .github/workflows/Covid19DataHub.yaml, .github/workflows/Cuba.yaml, .github/workflows/ECDC.yaml, .github/workflows/Estonia.yaml, .github/workflows/France.yaml, .github/workflows/Germany.yaml, .github/workflows/Google.yaml, .github/workflows/India.yaml, .github/workflows/Italy.yaml, .github/workflows/JHU.yaml, .github/workflows/JRC.yaml, .github/workflows/Lithuania.yaml, .github/workflows/Mexico.yaml, .github/workflows/Netherlands.yaml, .github/workflows/SouthAfrica.yaml, .github/workflows/Switzerland.yaml, .github/workflows/UK.yaml, .github/workflows/USA.yaml, .github/workflows/WHO.yaml
=> Run relevant tests on file change
